### ISSUE TITLE
Errors under docker and server only instance

### ISSUE THREAD

**Issue by a-waider** [XBCreepinJesus/MMM-ServerStatus#6]
Hi there,

I'm running Magic Mirror in server only mode using [this](https://hub.docker.com/r/karsten13/magicmirror) docker container.

Couldn't get this module to work properly. Does this error message tell you anything?

[02.09.2021 16:07.04.038] [ERROR] (node:41) UnhandledPromiseRejectionWarning: Error: ping.probe: there was an error while executing the ping program. . Check the path or permissions...
    at ChildProcess.<anonymous> (/opt/magic_mirror/modules/MMM-ServerStatus/node_modules/ping/lib/ping-promise.js:61:19)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[02.09.2021 16:07.04.039] [ERROR] (node:41) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing
inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by a-waider** [comment]
Nevermind, the ping package is not installed in the docker image.
